fa15-hw4/config/routes.rb
Rails.application.routes.draw do
  # users route
  get "users", to: "users#index"
  get "users/new", to: "users#new"
  get "users/:id", to: "users#show", as: :user
  post "users", to: "users#create"

  # dog routes
  # resources :dogs
  get "dogs", to: "dogs#index"
  get "dogs/new", to: "dogs#new"
  get "dogs/:id", to: "dogs#show", as: :dog
  post "dogs", to: "dogs#create"
end

fa15-hw4/app/models/dog.rb
class Dog < ActiveRecord::Base
    validates :name, presence: true
    validates :age, presence: true
end

fa15-hw4/app/models/user.rb
class User < ActiveRecord::Base
  # The User model.  Our abstraction to access the database.

  validates :name, presence: true # Validates that there is a name
end

fa15-hw4/app/controllers/dogs_controller.rb
class DogsController < ApplicationController
    def index
        @dogs = Dog.all
    end
    def new
        @dog = Dog.new
    end
    def create
        @dog = Dog.new(dog_params)
        if @dog.save
            redirect_to @dog, alert: "Dog created successfully"
        else
            redirect_to new_dog_path, alert: "Error creating Dog"
        end
        # @dog = Dog.new
        # @dog.name = params[:name]
        # @dog.age = params[:age]
        # @dog.save
    end
    def show
        @dog = Dog.find(params[:id])
        if @dog == nil
            @failed = true
        else
            @failed = false
        end
    end
    private
    def dog_params
        params.require(:dog).permit(:name, :age)
    end
end

fa15-hw4/app/controllers/users_controller.rb
class UsersController < ApplicationController
  # The controller for users.  Makes an implicit call to render "views/users/method_name.html.erb" at the end of every method.

  def index
    @users = User.all # Get's all the Users in our database and assigns it the the instance variable @user.
  end

  def new
    @user = User.new #Creates an empty user object.
  end

  def create
    @user = User.create(user_params)
    if @user.save #If saving the user was successful
      redirect_to @user #Go to the show view of the user
    else
      render "new" #Go to the new view for the user
    end
  end

  def show
    @user = User.find(params[:id]) # Query for the user with the id that is in params
  end

  private

  def user_params
    params.require(:user).permit(:name, :email) #Returns a hash that was the value of "name" and "email" from the value of "user" in params.
  end
end

fa15-hw4/app/helpers/dogs_helper.rb
module DogsHelper
end

fa15-hw4/app/helpers/users_helper.rb
module UsersHelper
end

fa15-hw4/app/views/dogs/create.html.erb
<%= link_to "Back", dogs_path %>
<h3>Created "<%= @dog.name%>", who is <%=@dog.age%> years old </h3>

fa15-hw4/app/views/dogs/index.html.erb
<h2>Do you like dogs? We do too!</h2>
<h4>Here's a list of our dogs:</h4>
<% @dogs.each do |d| %>
    <%= link_to d.name, d%>
<% end %>
<h4>Want to create a new dog? Click the new</h4>
<%= link_to "new", dogs_new_path %>

fa15-hw4/app/views/dogs/new.html.erb
<%= link_to "Back", dogs_path %>
<h3>Make a new Dog: </h3>
<%= form_for @dog, url: {action: "create"} do |dag|%>
    <%= dag.label "Name:"%>
    <%= dag.text_field :name%>
    <%= dag.label "Age:"%>
    <%= dag.text_field :age%>
    <%= dag.submit "Create Dog"%>
<% end %>

<!-- <%= form_tag("/dogs/create", method: "post") do %>
    <%= label_tag(:name, "Dog's Name: ") %>
    <%= text_field_tag(:name) %>
    <%= label_tag(:age, "Dog's Age: ") %>
    <%=  text_field_tag(:age) %>
    <%= submit_tag("Create dog") %>
<% end %> -->

fa15-hw4/app/views/dogs/show.html.erb
<%= link_to "Back", dogs_path %>
<% if @failed %>
    <h3>COULDN'T FIND DOG WITH THIS ID!!!!!</h3>
<% else %>
    <h3><%=@dog.name%> is <%=@dog.age%> years old!</h3>
<% end %>

fa15-hw4/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fa15Hw4</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

fa15-hw4/app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

fa15-hw4/app/views/users/index.html.erb
<h1>Users in the Database</h1>
<% @users.each do |u| %> <!-- Iterates through each user under the variable u -->
  Name: <p> <%= link_to u.name, user_path(u) %> </p> <!-- Show the users name-->
  Email : <p> <%= u.email %> </p> <!-- Show the users email -->
<% end %>
<%= link_to "new", users_new_path %> <!-- Create a link that appears as "new" that leads to users_new_path -->

fa15-hw4/app/views/users/new.html.erb
<h1>Create New</h1>
  <%= form_for @user do |f| %> <!-- Create form for user object -->
    Name: <%= f.text_field :name %> <!-- Create a text field that sends its value under the key name-->
    Email: <%= f.text_field :email %><!-- Create a text field that sends its value under the key email -->
    <%= f.submit %> <!-- Create submit button-->
  <% end %>


<p>Find me in app/views/users/new.html.erb</p>

fa15-hw4/app/views/users/show.html.erb
Name: <%= @user.name %>
Email: <%= @user.email %>